### ISSUE TITLE
unable to recognize "https://raw.githubusercontent.com/yametech/compass/master/kubernetes/release.yml": no matches for kind "BaseDepartment" in version "fuxi.nip.io/v1"

### ISSUE THREAD

**Issue by tscswcn** [yametech/compass#43]
kubectl apply -f https://raw.githubusercontent.com/yametech/compass/master/kubernetes/release.yml 
.........
unable to recognize "https://raw.githubusercontent.com/yametech/compass/master/kubernetes/release.yml": no matches for kind "BaseDepartment" in version "fuxi.nip.io/v1"
unable to recognize "https://raw.githubusercontent.com/yametech/compass/master/kubernetes/release.yml": no matches for kind "BaseUser" in version "fuxi.nip.io/v1"

**Comment by withlin** [comment]
@tscswcn hi, i think that you k apply again.

**Comment by withlin** [comment]
already fix. your env problem. /close
